backend:
  name: github
  repo: betagouv/preuve-covoiturage-vitrine
  branch: beta

media_folder: src/static/images
public_folder: images

locale: fr

slug:
  clean_accents: true

collections:
  - label: "📄 Pages"
    name: pages
    files:
      - label: "👥 Qui sommes-nous ?"
        name: qui-sommes-nous
        file: src/content/qui-sommes-nous/_index.md
        editor:
          preview: false
        fields:
          - label: Titre
            name: title
            widget: string
          - label: Sous-titre
            name: subtitle
            widget: text
          - label: Actions
            name: actions
            widget: list
            fields:
              - label: Titre
                name: title
                widget: string
              - label: Lien
                name: href
                widget: string
              - label: Style
                name: style
                widget: select
                multiple: false
                options:
                  - primary
                  - secondary
                default: primary
                required: false
          - label: Contenu
            name: body
            widget: markdown

      - label: "🚘 Opérateurs"
        name: operateurs
        file: src/content/operateurs/_index.md
        editor:
          preview: false
        fields:
          - label: Titre
            name: title
            widget: string
          - label: Sous-titre
            name: subtitle
            widget: text
          - label: Actions
            name: actions
            widget: list
            fields:
              - label: Titre
                name: title
                widget: string
              - label: Lien
                name: href
                widget: string
              - label: Style
                name: style
                widget: select
                multiple: false
                options:
                  - primary
                  - secondary
                default: primary
                required: false
          - label: "Titre des opérateurs liés"
            name: section_linked_title
            widget: string
          - label: "Titre des opérateurs non liés"
            name: section_notlinked_title
            widget: string

      - label: "🏛️ Territoires"
        name: territoires
        file: src/content/territoires/_index.md
        editor:
          preview: false
        fields:
          - label: Titre
            name: title
            widget: string
          - label: Sous-titre
            name: subtitle
            widget: text
          - label: Actions
            name: actions
            widget: list
            fields:
              - label: Titre
                name: title
                widget: string
              - label: Lien
                name: href
                widget: string
              - label: Style
                name: style
                widget: select
                multiple: false
                options:
                  - primary
                  - secondary
                default: primary
                required: false
          - label: Contenu
            name: body
            widget: markdown

  - label: "📝 Blocks"
    name: blocks
    files:
      - label: "🙋 Vous êtes..."
        name: vousetes
        file: src/data/vousetes.yml
        editor:
          preview: false
        fields:
          - label: Titre
            name: title
            widget: string
          - label: Cartes
            label_singular: carte
            name: cards
            widget: list
            fields:
              - label: Titre
                name: title
                widget: string
              - label: Description
                name: description
                widget: string
              - label: Bouton
                name: link_title
                widget: string
              - label: Lien
                name: link_href
                widget: string

      - label: "😉 Témoignages"
        name: testimonials
        label_singular: Témoignage
        file: src/data/testimonials.yml
        editor:
          preview: false
        fields:
          - label: Titre
            name: title
            widget: string
          - label: Témoignages
            label_singular: Témoignage
            name: cards
            widget: list
            fields:
              - label: Aute·ur·rice
                name: title
                widget: string
              - label: Témoignage
                name: description
                widget: text
              - label: Logo
                name: logo
                widget: image
                required: false

      - label: "📈 Statistiques"
        name: stats
        label_singular: Statistique
        file: src/data/stats.yml
        editor:
          preview: false
        fields:
          - label: Titre
            name: title
            widget: string
          - label: Statistiques
            label_singular: Statistique
            name: cards
            widget: list
            fields:
              - label: Description
                name: description
                widget: markdown
              - label: "Visible sur la page d'accueil"
                name: pinned
                widget: boolean
                default: false
              - label: Image
                name: image
                widget: image
                required: false
              - label: Titre du lien
                name: link_title
                widget: string
                required: false
              - label: Lien
                name: link_href
                widget: string
                required: false

  - name: operateurs
    label: "🚘 Opérateurs"
    label_singular: Opérateur
    folder: src/content/operateurs
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    filter:
      field: filter
      value: operateur
    fields:
      - label: Nom
        name: title
        widget: string
      - label: Publication
        name: date
        widget: datetime
        date_format: "DD/MM/YYYY"
        time_format: "HH:mm"
        picker_utc: false
      - label: "Connecté au RPC"
        name: linked
        widget: boolean
        default: false
      - label: Logo
        name: logo
        widget: image
        required: false
        allow_multiple: false
        media_folder: /src/static/images/operateurs
        public_folder: /images/operateurs
      - label: "Site web"
        name: link
        widget: string
        required: false

  - name: territoires
    label: "🏛️ Territoires"
    label_singular: Territoire
    folder: src/content/territoires
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    filter:
      field: filter
      value: territoire
    fields:
      - label: Nom
        name: title
        widget: string
      - label: Publication
        name: date
        widget: datetime
        date_format: "DD/MM/YYYY"
        time_format: "HH:mm"
        picker_utc: false
      - label: "Afficher le nom"
        name: showTitle
        widget: boolean
        default: true
      - label: Logo
        name: logo
        widget: image
        required: false
        allow_multiple: false
        media_folder: /src/static/images/operateurs
        public_folder: /images/operateurs
