backend:
  name: github
  repo: betagouv/preuve-covoiturage-vitrine
  branch: beta
  site_domain: distracted-turing-4b85e9.netlify.app

media_folder: src/static/images
public_folder: images

locale: fr

slug:
  clean_accents: true

collections:
  - name: "operateurs"
    label: "Opérateurs"
    label_singular: "Opérateur"
    folder: src/content/operateurs
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Nom", name: "title", widget: "string" }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          date_format: "DD/MM/YYYY",
          time_format: "HH:mm",
          picker_utc: false,
        }
      - { label: "Connecté au RPC", name: "linked", widget: "boolean", default: false }
      - {
          label: "Logo",
          name: "logo",
          widget: "image",
          required: false,
          allow_multiple: false,
          media_folder: "/src/static/images/operateurs",
          public_folder: "/images/operateurs",
        }
      - { label: "Site web", name: "link", widget: "string", required: false }

  - name: "territoires"
    label: "Territoires"
    label_singular: "Territoire"
    folder: src/content/territoires
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Nom", name: "title", widget: "string" }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          date_format: "DD/MM/YYYY",
          time_format: "HH:mm",
          picker_utc: false,
        }
      - { label: "Afficher le nom", name: "showTitle", widget: "boolean", default: true }
      - {
          label: "Logo",
          name: "logo",
          widget: "image",
          required: false,
          allow_multiple: false,
          media_folder: "/src/static/images/territoires",
          public_folder: "/images/territoires",
        }
