version: "3"
services:
  hugo:
    image: klakegg/hugo:0.79.1-ext
    volumes:
      - "./src:/src"
      - "./public:/public"
  server:
    image: klakegg/hugo:0.79.1-ext
    command: server
    volumes:
      - "./src:/src"
    ports:
      - "1313:1313"
