[build]
base = "src"
publish = "public-netlify"
command = "hugo --gc --minify -d public-netlify -e beta"

[context.production.environment]
HUGO_VERSION = "0.82.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.beta.environment]
HUGO_VERSION = "0.82.0"
HUGO_ENV = "beta"
HUGO_ENABLEGITINFO = "true"
