name = "dsfr"
license = "Apache-2.0"
licenselink = "https://www.apache.org/licenses/LICENSE-2.0.txt"
description = "Design System de l'Etat Français"
homepage = "https://template.incubateur.net/"
tags = []
features = []
min_version = "0.79.1"

[author]
  name = "DINUM - beta.gouv"
  homepage = "https://template.incubateur.net/"
