name = "2021"
license = "Apache-2.0"
licenselink = "https://www.apache.org/licenses/LICENSE-2.0.txt"
description = "Registre de preuve de covoiturage 2021"
homepage = "https://covoiturage.beta.gouv.fr/"
tags = []
features = []
min_version = "0.79.1"

[author]
  name = "Registre de preuve de covoiturage"
  homepage = "https://covoiturage.beta.gouv.fr/"
